- name: get playwright pod-name
  shell:
    kubectl get pods | grep playwright | awk '{print $1}'
  register: pod_name

- name: Print pod name
  debug:
    msg: "The pod name is {{pod_name.stdout}} "

- name: exec in this pod and run test
  shell:
    kubectl exec {{pod_name.stdout}} -- /bin/bash -c "cd /home/pwuser/files |node test.js"
